### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yaron2**
Fix typos.

### CODE REVIEW

**Comment by stefanberger** [comment]
Your patch is failing the tests since it is missing a Signed-off-by.

**Comment by yaron2** [comment]
> LGTM with signature added to the commit
> please git commit -s --amend

I did, it's still failing..

**Comment by lumjjb** [comment]
All the commits have to be signed, including previous ones... my suggestion is to either rebase it on master and squash everything or you could just recreate a new branch and apply the changes you've made (and either make a new PR or do a force push here).

**Comment by stefanberger** [comment]
The fixes from this PR have been merge via other PRs.

**Pull request closed without merging**
