### PR TITLE
[Carry #50] separate command-line to a separate module

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Carry:
- #50

Rebased and removed the entire `vendor/` dir for simplicity.

### CODE REVIEW

**Review by mikebrow — APPROVED** [review]
LGTM

**Comment by AkihiroSuda** [comment]
ping @thaJeztah @stefanberger @lumjjb

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Review by stefanberger — APPROVED** [review]
LGTM

**Pull request merged**
