### PR TITLE
Migrate to GitHub Actions for CI

### PR DESCRIPTION
**Pull request by estesp**
This enables GitHub actions for both Linux and Windows and runs the same checks/tests as currently implemented via Travis and Appveyor. If acceptable, Travis and Appveyor can be removed once validated; a successful run is here in my fork: https://github.com/estesp/imgcrypt/actions/runs/615320837

### CODE REVIEW

**Comment by stefanberger** [comment]
Can we now also remove the vendor directory?

**Comment by stefanberger** [comment]
Someone with more rights to change the settings of this project should probably enable github actions so that we see them running form now on.

**Comment by stefanberger** [comment]
@estesp Thanks for the PR!

**Comment by estesp** [comment]
As soon as this is merged you will automatically start to see the actions runs on every future PR and merge. No settings need to be changed. At that point we can remove the Travis config file and that will automatically stop Travis from running

**Comment by stefanberger** [comment]
LGTM

**Pull request merged**
