### PR TITLE
Bump containerd to 1.5.2

### PR DESCRIPTION
**Pull request by aledbf**
Upgrade containerd to 1.5.2

Signed-off-by: Manuel Alejandro de Brito Fontes aledbf@gmail.com

### CODE REVIEW

**Comment by stefanberger** [comment]
I think you will have to run a vendor update as well.

**Comment by aledbf** [comment]
@stefanberger done

**Review by lumjjb — APPROVED** [review]
LGTM

**Comment by stefanberger** [comment]
LGTM.

**Pull request merged**
