### PR TITLE
Add pkcs11 support to imgcrypt's ctr-enc

### PR DESCRIPTION
**Pull request by stefanberger**
This PR does some dependency cleanups and then adds pkcs11 support to ctr-enc.

### CODE REVIEW

**Comment by lumjjb** [comment]
can we squash this to vendor updates and the pkcs11 changes in the event we need to temporarily revert the pkcs11 change.

**Comment by stefanberger** [comment]
> can we squash this to vendor updates and the pkcs11 changes in the event we need to temporarily revert the pkcs11 change.

Which one is 'this'? ` ctr-enc: Add warning about pkcs11 usage currently being experimental `?

**Comment by lumjjb** [comment]
I see these commits, is this just a git issue then?

```
@stefanberger
vndr: Run vndr and remove some .mod files …
83c001d
@stefanberger
vndr: Switch to recent ocicrypt and recent pkcs7 …
91db82f
@stefanberger
vndr: Switch to latest ocicrypt and add dependencies …
e0d199e
@stefanberger
images: Move functions into parse_helpers.go to resemble ocicrypt …
0fe1e71
@stefanberger
Create CreateCryptoConfig in parse_helpers and have encrypt.go use it. …
ad9efb9
```

**Comment by stefanberger** [comment]
Maybe splitting off the vendor and module updates from `Add pkcs11 support` would help a bit?

**Comment by stefanberger** [comment]
This is the order of the series:

```
d97fe09 (HEAD -> pkcs11, origin/pkcs11) ctr-enc: Add warning about pkcs11 usage currently being experimental
512162d Extend test script with PKCS11 test case and adjust Travis config file
287eb7a Add pkcs11 support
ad9efb9 Create CreateCryptoConfig in parse_helpers and have encrypt.go use it.
0fe1e71 images: Move functions into parse_helpers.go to resemble ocicrypt
e0d199e vndr: Switch to latest ocicrypt and add dependencies
91db82f vndr: Switch to recent ocicrypt and recent pkcs7
83c001d vndr: Run vndr and remove some .mod files
```

**Comment by stefanberger** [comment]
I squashed the vndr patches now and pulled the modules update out of the `Add pkcs11 support` patch. So the last 3 patches now have the pkcs11 support.

```
bb46e40 (HEAD -> pkcs11, origin/pkcs11) ctr-enc: Add warning about pkcs11 usage currently being experimental
6a4f718 Extend test script with PKCS11 test case and adjust Travis config file
bff618b Add pkcs11 support
47e60dc modules: Move to latest ocicrypt go module
936d286 Create CreateCryptoConfig in parse_helpers and have encrypt.go use it.
69cf6a0 images: Move functions into parse_helpers.go to resemble ocicrypt
d3c2394 vndr: Switch to recent ocicrypt and recent pkcs7
```

**Comment by stefanberger** [comment]
Are all comments addressed now and can we merge it ?

**Review by lumjjb — APPROVED** [review]
LGTM!

**Comment by stefanberger** [comment]
Thanks!

**Pull request merged**
