### PR TITLE
go.mod: github.com/containerd/containerd/v2 v2.0.0-rc.6

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
lint fails without showing any reason

**Comment by stefanberger** [comment]
> lint fails without showing any reason

I don't see anything on my machine ... except it timed out.

**Comment by stefanberger** [comment]
Can you rebase on latest main?

**Comment by stefanberger** [comment]
Thanks.

**Pull request merged**
