### PR TITLE
go.mod: github.com/containerd/containerd v2.0.0-rc.3

### PR DESCRIPTION
**Pull request by thaJeztah**
- relates to https://github.com/containerd/containerd/pull/10330
- relates to https://github.com/containerd/containerd/pull/10357

rc.3 rmoves pkg/seed, so removing that import from cmd/ctr

full diff: https://github.com/containerd/containerd/compare/v2.0.0-rc.2...v2.0.0-rc.3

### CODE REVIEW

**Review by stefanberger — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
@stefanberger @lumjjb Can we make a new release?

**Comment by stefanberger** [comment]
> @stefanberger @lumjjb Can we make a new release?

Why not wait until v2.0.0 has been released?

**Comment by AkihiroSuda** [comment]
Because containerd v2 vendors a "random main commit" of imgcrypt.
The new release of imgcrypt should be like v2.0.0-rc.0 perhaps

**Comment by thaJeztah** [comment]
> The new release of imgcrypt should be like v2.0.0-rc.0 perhaps

Does it need a major version update? 😬 (if that's the case, there's probably a lot more to do; updating import paths everywhere)

**Comment by AkihiroSuda** [comment]
Can be also v1.2.0-rc.0

**Comment by stefanberger** [comment]
I tagged v1.2.0-rc1.

**Pull request merged**
