### PR TITLE
Update to ocicrypt 1.1.6 and add support for zstd type of compressed layers 

### PR DESCRIPTION
**Pull request by stefanberger**
Update to ocicrypt 1.1.6 and add support for zstd type of compressed layers

### CODE REVIEW

**Comment by k-gostev** [comment]
@stefanberger Thanks a lot for your fast reaction, I really appreciate it!
I did not test it but I would guess that the `zstd` media type checks should also be added in the [decrypt](https://github.com/containerd/imgcrypt/blob/2c93cef1eb0b48263d16f5f2289a1a3f49a17d39/images/encryption/encryption.go#L134-L179) functions as well.

**Comment by stefanberger** [comment]
> I did not test it but I would guess that the `zstd` media type checks should also be added in the [decrypt](https://github.com/containerd/imgcrypt/blob/2c93cef1eb0b48263d16f5f2289a1a3f49a17d39/images/encryption/encryption.go#L134-L179) functions as well.

Added that now. Thanks.

**Comment by stefanberger** [comment]
Thanks for providing the steps. After another fix I can now encrypt end decrypt with zstd-compressed images.

**Comment by stefanberger** [comment]
It works for me, if it works for you @k-gostev as well , let me know and I'll merge it.

**Review by lumjjb — APPROVED** [review]
LGTM

**Comment by k-gostev** [comment]
Works for me as well. Thank you!
LGTM

**Comment by k-gostev** [comment]
BTW could you tell me what are your plans about the next release that will include this fix? When could be expected?

**Comment by stefanberger** [comment]
I can tag in the next few days.

**Comment by stefanberger** [comment]
@k-gostev I tagged v1.1.7 now.

**Pull request merged**
