### PR TITLE
Move to go modules

### PR DESCRIPTION
**Pull request by chenrui333**
Issue tracker, https://github.com/containerd/containerd/issues/3031

### CODE REVIEW

**Comment by lumjjb** [comment]
@chenrui333 thanks for the PR! Looks good but CI is failing. I believe may be because of this line:

https://github.com/containerd/imgcrypt/blob/master/script/setup/install-runc#L24

Which needs to be updated to parse go mod instead of vendor.conf.

**Comment by chenrui333** [comment]
@lumjjb I will spend some time tomorrow on this, too busy today. :)

**Comment by lumjjb** [comment]
Awesome! No worries. Thanks! :D

**Comment by chenrui333** [comment]
FYI, I will spend more time on this later today or tomorrow. :)

**Comment by lumjjb** [comment]
@chenrui333 Happy New Year! How are things going?

**Comment by chenrui333** [comment]
@lumjjb Happy new year!!

**Pull request merged**
