### PR TITLE
Update go module to imgcrypt v2

### PR DESCRIPTION
**Pull request by dmcgowan**
Allow importing of containerd v2 without breaking compatibility for use with containerd v1.

For consideration of creating v2.0.0 tag over v1.2.0 to allow continued use with containerd 1.x.

Note there is no need for cmd module to also go to v2 but it could be considered as well.

### CODE REVIEW

**Comment by stefanberger** [comment]
Thanks.

**Comment by AkihiroSuda** [comment]
Can we tag a new version?

**Comment by stefanberger** [comment]
> Can we tag a new version?

Latest tag is v1.2.0-rc1. Now tag it with v1.2.0?

**Comment by stefanberger** [comment]
> > Can we tag a new version?
> 
> Latest tag is v1.2.0-rc1. Now tag it with v1.2.0?

Actually, maybe only v1.2.0-rc2 now that it depends on a contained rc still `github.com/containerd/containerd/v2 v2.0.0-rc.6`.

**Comment by AkihiroSuda** [comment]
IIUC the intent of this PR is to have v2.0.0[-rc.0]

**Comment by stefanberger** [comment]
> IIUC the intent of this PR is to have v2.0.0[-rc.0]

Well, we are still depending on v2.0.0-rc.6 of containerd. Because of this we probably still have to work with an rc. And you mean imgcrypt should pick up the version number of upcoming containerd, so tag it with v2.0.0-rc.1 instread of v.1.2.0-rc2?

**Comment by AkihiroSuda** [comment]
> > IIUC the intent of this PR is to have v2.0.0[-rc.0]
> 
> Well, we are still depending on v2.0.0-rc.6 of containerd. Because of this we probably still have to work with an rc. And you mean imgcrypt should pick up the version number of upcoming containerd, so tag it with v2.0.0-rc.1 instread of v.1.2.0-rc2?

Yes, as this is a breaking change of the Go API
(So, imgcrypt v2.1 won't need to be synced with containerd v2.1)

**Comment by stefanberger** [comment]
I tagged it now with v2.0.0-rc.1.

**Comment by AkihiroSuda** [comment]
Thanks!

**Pull request merged**
